---
- name: Setup for nfs server  # 플레이1
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: make nfs_shared directory # 공유 디렉토리 생성
      file:
        path: /home/vagrant/nfs_shared
        state: directory
        mode: 0777                          

    - name: configure /etc/exports  # 공유 디렉토리 export
      become: yes
      lineinfile:
        path: /etc/exports
        line: /home/vagrant/nfs_shared 192.168.219.0/24(rw,sync)

    - name: nfs service restart
      become: yes
      service:
        name: nfs
        state: restarted

- name: Setup for nfs clients   # 플레이2
  hosts: CentOS:Ubuntu
  gather_facts: no

  tasks:
    - name: make nfs_client directory
      file:
        path: /home/vagrant/nfs
        state: directory

    - name: mount point directory as client
      become: yes
      mount:
        path: /home/vagrant/nfs
        src: 192.168.219.10:/home/vagrant/nfs_shared  # 앤서블 서버에 있는 공유 디렉토리 마운트
        fstype: nfs
        opts: nfsvers=3
        state: mounted