---
- name: Remove nginx on CentOS
  hosts: CentOS # 대상 노드들 명시(node01, node02)
  gather_facts: no
  become: yes

  tasks:
    - name: remove epel-release
      yum: name=epel-release state=absent
    - name: remove nginx web server
      yum: name=nginx state=absent

- name: Remove nginx on Ubuntu
  hosts: Ubuntu
  gather_facts: no
  become: yes

  tasks:
    - name: remove nginx web server
      apt: pkg=nginx state=absent autoremove=yes